
name: Check POWERLIB

on:
  push:
    branches:
      - modular-refactor
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python syntax
        run: python -m compileall -q bot.py handlers modules
